#!/usr/bin/env python3
"""Rebuild data/companionIndex.ts from known_faces + photo_names."""

from __future__ import annotations

import json
import re
from collections import defaultdict
from pathlib import Path

from config import META_DIR, PROJECT_ROOT

OUT = PROJECT_ROOT / "data" / "companionIndex.ts"
COMPANION_LABEL = re.compile(r"^(.+?)\s*眷\d*$")


def main() -> None:
    known = json.loads((META_DIR / "known_faces.json").read_text(encoding="utf-8"))
    photo_names = json.loads((META_DIR / "photo_names.json").read_text(encoding="utf-8"))

    by_host: dict[str, set[str]] = defaultdict(set)

    for entry in known.values():
        if not isinstance(entry, dict):
            continue
        host = (entry.get("companionOfName") or "").strip()
        name = (entry.get("name") or "").strip()
        if host and name and name != host:
            by_host[host].add(name)

    for payload in photo_names.values():
        for label in payload.get("names") or []:
            match = COMPANION_LABEL.match(str(label).strip())
            if not match:
                continue
            host = match.group(1).strip()
            if host:
                by_host[host].add(str(label).strip())

    items = {host: sorted(names) for host, names in sorted(by_host.items(), key=lambda x: x[0])}

    lines = [
        "/** Host guest name → companion display names appearing on photos. */",
        "/** Regenerated by scripts/wedding_faces/generate_companion_index.py */",
        "export const COMPANIONS_BY_HOST: Record<string, readonly string[]> = {",
    ]
    for host, names in items.items():
        arr = ", ".join(json.dumps(name, ensure_ascii=False) for name in names)
        lines.append(f"  {json.dumps(host, ensure_ascii=False)}: [{arr}],")
    lines.append("};")
    lines.append("")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} ({len(items)} hosts, {sum(len(v) for v in items.values())} companions)")


if __name__ == "__main__":
    main()
